-- İzolasyon ürün adlarını çoklu ürün formatına güncelle
-- Görseldeki listeye göre

-- DİKKAT: Bu script mevcut verileri silmez, sadece YENİ ürünler ekler
-- Format: "ÜRÜN-KOD (TİP)" veya "ÜRÜN-KOD1 (TİP) - ÜRÜN-KOD2 (TİP)"

INSERT INTO mamul_izolasyon (name, cin_adi, turk_adi, renk, stock, created_at, updated_at)
VALUES
  ('FOG-B335A (A)', NULL, NULL, NULL, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('FOG-B335A (B) - FOG-B506A (B)', NULL, NULL, NULL, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('FOG-B730A (B)', NULL, NULL, NULL, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('FOG-B1350 (A)', NULL, NULL, NULL, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('FOG-B1350A (B)', NULL, NULL, NULL, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('HZG20B (B) - HZG30B (D)', NULL, NULL, NULL, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('HZG20B (A) - HZG30B (B)', NULL, NULL, NULL, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('HZG30B (A)', NULL, NULL, NULL, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('HZG30B (C) - FQ-01B/A (A)', NULL, NULL, NULL, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('FQ01B/A-B', NULL, NULL, NULL, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('KHRQ22M20T (A)', NULL, NULL, NULL, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('KHRQ22M20T (B)', NULL, NULL, NULL, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('MXJ-YA1509M/R1 (A) - MXJ-YA1500M', NULL, NULL, NULL, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('MXJ-YA1509M/R1 (B) - MXJ-YA2812M (B) - MXJ-YA2815M (B) - MXJ-YA3419M (B)', NULL, NULL, NULL, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('MXJ-YA2812M (A) - MXJ-YA2815M (A)', NULL, NULL, NULL, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('MXJ-YA3419M (A) - MXJ-YA4119M (A)', NULL, NULL, NULL, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('MXJ-YA4119M (B)', NULL, NULL, NULL, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('FOG-B335A/Y (A)', NULL, NULL, NULL, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('FOG-B335A/Y (B)', NULL, NULL, NULL, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('MXJ-YA2512M/R3 (B)', NULL, NULL, NULL, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('MXJ-YA2512M/R3 (A)', NULL, NULL, NULL, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('FOG-B506A/Y (A) - FOG-B730A (A)', NULL, NULL, NULL, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('FOG-B506A/Y (B)', NULL, NULL, NULL, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('FOG-B506A (A) - FOG-B730A (A)', NULL, NULL, NULL, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('X', NULL, NULL, NULL, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('FOG-B730A/Y (B)', NULL, NULL, NULL, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('CMY-Y102SS-TR (A)', NULL, NULL, NULL, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('CMY-Y102SS-TR (B)', NULL, NULL, NULL, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('CMY-102L-A (A) - CMY-202S (A)', NULL, NULL, NULL, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('CMY-102L-B', NULL, NULL, NULL, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('CMY-202S (B)', NULL, NULL, NULL, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- NOT:
-- 1. Bu script tüm izolasyonları temizleyip yeni formatta ekler
-- 2. Çin adı (cin_adi) ve Türk adı (turk_adi) alanlarını düzenleme modalı ile doldurabilirsiniz
-- 3. Renk bilgilerini düzenleme modalı ile ekleyebilirsiniz
-- 4. Stok sayıları sıfır olarak başlar, "Stok Değiştir" butonu ile güncellenebilir
-- 5. "X" satırı görselde belirsiz olduğu için placeholder olarak eklendi
