// Hatalı Ürünler Modülü için Ürün Listesi
export const URUN_LISTESI = [
  'MXJ-YA2512M/R (A)',
  'MXJ-YA2512M/R (B)',
  'DIS-371-2GAT (A)',
  'DIS-371-2GAT (B)',
  'DIS-180-2GAT (A)',
  'DIS-180-2GAT (B)',
  'DIS-22-1GAT (A)',
  'DIS-22-1GAT (B)',
  'KHRQ22M20T (A)',
  'KHRQ22M20T (B)',
  'FQG-335A (A)',
  'FQG-335A (B)',
  'FQG-335A-Y (A)',
  'FQG-335A-Y (B)',
  'FQG-B506A-Y (A)',
  'FQG-B506A-Y (B)',
  'FQG-B730A-Y (A)',
  'FQG-B730A-Y (B)',
  'MXJ-YA1509M-R1 (A)',
  'MXJ-YA1509M-R1 (B)',
  'MXJ-YA2815M/R (A)',
  'MXJ-YA2815M/R (B)',
  'CMY-Y102SS-TR (A)',
  'CMY-Y102SS-TR (B)',
  'FQG-04NAaA (A)',
  'FQG-04NAaA (B)',
  'HZG-30B (A)',
  'HZG-30B (B)',
  'HZG-30B (C)',
  'HZG-30B (D)',
  'HZG-20B (A)',
  'HZG-20B (B)',
  'FQG-B1350A (A)',
  'FQG-B1350A (B)',
  'FQG-B506 (A)',
  'FQG-B506 GRİ (B)',
  'FQG-B730 (A)',
  'FQG-B730 GRİ (B)',
  'FQ01B/A (A)',
  'FQ01B/A (B)',
  'FQ01B/A (C)'
];

// Hata Tipleri
export const HATA_TIPLERI = [
  { key: 'temizleme_problemi', label: 'Temizleme Problemi' },
  { key: 'vuruk_problem', label: 'Vuruk Problem' },
  { key: 'capagi_alinmayan', label: 'Çapağı Alınmayan' },
  { key: 'polisaj', label: 'Polisaj' },
  { key: 'kaynak_az', label: 'Kaynak Az' },
  { key: 'kaynak_akintisi', label: 'Kaynak Akıntısı' },
  { key: 'ici_capakli', label: 'İçi Çapaklı' },
  { key: 'pim_girmeyen', label: 'Pim Girmeyen' },
  { key: 'boncuklu', label: 'Boncuklu' },
  { key: 'yamuk', label: 'Yamuk' },
  { key: 'gramaji_dusuk', label: 'Gramajı Düşük' },
  { key: 'hurda', label: 'Hurda' }
];
